title: Blog
description: "Blog of embedded dev."
baseurl: ""
url: ""
github_username: szymonhrehorowicz

remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-feed
  - jekyll-remote-theme

plainwhite:
  name: Szymon Hrehorowicz
  tagline: Dev
  date_format: "%b %-d, %Y"
  portfolio_image: "assets/portfolio.png"
  show_sidebar: true
  dark_mode: true

  social_links:
    github: szymonhrehorowicz
    linkedIn: in/szymon-hrehorowicz-277118183
